# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e57a1912538e942058eaf430ee61973a353a6ef361ec6055e2f13c2935f92c4b201984e04a6903bcbc1cc05d923175aef39733f4ecf3ac6466d660c12afbd47e

test:
  secret_key_base: 84845f31b9370bff3d204590690667fde149441305dfe3893a6692ec6db6361b81bd6c0becd2979449b38d3505242396fe3868084e19abbad8fd6055504b9a47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
